version: "3.8"

services:

  postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "simple-delivery-database"
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./main.sql:/docker-entrypoint-initdb.d/main.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq-simple-delivery"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs

volumes:
  postgresql:

networks:
  rabbitmq_nodejs:
    driver: bridge
