@HOST = http://localhost:8080

# @name auth
POST {{HOST}}/auth/managers HTTP/1.1
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "example"
}
###

POST {{HOST}}/auth/clients HTTP/1.1
Content-Type: application/json

{
  "email": "exampl3@gmail.com",
  "password": "example"
}
###

POST {{HOST}}/auth/select-store HTTP/1.1
Content-Type: application/json

{
  "storeId": "a63b601f-7a26-4ca8-a25b-b24d87390ac4"
}
###

# @name register
POST {{HOST}}/managers HTTP/1.1
Content-Type: application/json

{
  "firstName": null,
  "lastName": "Segundo nome",
  "email": "example4@gmail.com",
  "password": "example"
}
###

POST {{HOST}}/clients HTTP/1.1
Content-Type: application/json

{
  "firstName": "Primeiro",
  "lastName": "Segundo nome",
  "email": "exampl3@gmail.com",
  "password": "example"
}
###

# @name stores
POST {{HOST}}/stores HTTP/1.1
Content-Type: applicati on/json

{
  "name": "minha loja"
}
###

GET {{HOST}}/stores/my HTTP/1.1
###

GET {{HOST}}/stores/3 HTTP/1.1
###

PUT {{HOST}}/stores HTTP/1.1
Content-Type: application/json

{
  "id": "a63b601f-7a26-4ca8-a25b-b24d87390ac4",
  "name": "salgados!"
}
###

# @name products
GET {{HOST}}/products/mine HTTP/1.1
###

POST {{HOST}}/products HTTP/1.1
Content-Type: application/json

{
  "name": "teste",
  "description": "teste",
  "price": 10
}
###
